collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2437276
  brandStrength: 0.3847633
  lightness: 0.3207885
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  rhythmicContrast: 0.7275985
typography_spectrum: 0.2992831
layout_spectrum: 0.9964158
name: FlyByMarketing
